### ISSUE TITLE
DefaultCredentialsError: Your default credentials were not found. To set up Application Default Credentials

### ISSUE THREAD

**Issue by leapyear1969** [MrGeislinger/ai-chat-ui#3]
when i communicate with gemini, it show below error.

**DefaultCredentialsError: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.**

i'm not familar with google api development, can you please give some advisory, thanks in advance.

![image](https://github.com/MrGeislinger/ai-chat-ui/assets/18607988/8aa454c6-5221-47a1-b7f8-33fb3f4a0dd1)

**Comment by leapyear1969** [comment]
after reading the google api's document from [https://cloud.google.com/iam/docs/keys-create-delete](https://cloud.google.com/iam/docs/keys-create-delete), adding below code to app_chat.py fixed this issue. 

```python 
# set google serviceaccount
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "/home/jason/Documents/my_service_account.json"
```

**Comment by MrGeislinger** [comment]
Great that you figured this out for your setup! But to clarify you could have also followed the ["Installation" section in the README](https://github.com/MrGeislinger/ai-chat-ui/tree/main?tab=readme-ov-file#install) to either add your API key (your secret string) to your environment variables (such as `.bashrc` or `.zshrc`) or directly copied into the file `app_chat.py` like below:

```python
# GOOGLE_API_KEY=os.environ.get('GOOGLE_API_KEY')
GOOGLE_API_KEY='867ajhgh5309'  # note this is just an example of your API key
```

You went the IAM route which is fine (if not the preferred method), but you also could have made a new API secret key from here https://ai.google.dev/tutorials/setup (same link given in the [README](https://github.com/MrGeislinger/ai-chat-ui/tree/main?tab=readme-ov-file#install))
